<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>Mar26_BDD</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>


    <dependencies>

        <!--        When, And, Then, @After & @Before-->
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>7.14.0</version>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit-platform-engine</artifactId>
            <version>7.14.0</version>
        </dependency>

        <!--        Allure Cucumber Junit 5-->

        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-cucumber7-jvm</artifactId>
            <version>2.32.0</version>
        </dependency>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-junit-platform</artifactId>
            <version>2.32.0</version>
        </dependency>

        <!--        Engine dependecy will identify the feature files and run it using surefire plaugin-->
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-engine</artifactId>
            <version>6.1.1</version>
        </dependency>

        <!--        For running the feature files, we need this dependency-->
        <!-- Source: https://mvnrepository.com/artifact/org.junit.platform/junit-platform-suite -->
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-suite</artifactId>
            <version>1.10.0</version>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.45.0</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.8.0</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.5</version>
                <configuration>
                    <systemPropertyVariables>
                        <browser>${browser}</browser>
                        <env>${env}</env>
                    </systemPropertyVariables>
                    <includes>
                        <include>**/TestRunner.java</include>
                    </includes>
                    <properties>
                        <configurationParameters>
                            cucumber.junit-platform.naming-strategy=long
                            cucumber.execution.parallel.enabled=true
                            cucumber.execution.parallel.config.strategy=fixed
                            cucumber.execution.parallel.config.fixed.parallelism=2
                            cucumber.publish.enabled=true
                            cucumber.publish.quiet=true
                            cucumber.plugin=io.qameta.allure.cucumber7jvm.AllureCucumber7Jvm
                            cucumber.filter.tags=${tags}
                            cucumber.execution.execution-mode.feature=concurrent
                            cucumber.execution.execution-mode.scenario=same_thread
                        </configurationParameters>
                    </properties>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>