#=========QA=================================================

QA.URL=http://34.66.197.232/#/access
QA.STUDENTID=35EGM7D45W
QA.ACCESSCODE=7MNT2R2F

QA.USEREMAIL=
QA.PASSWORD=


#=========STAGE=================================================

STAGE.URL=http://34.66.197.232/#/access
STAGE.STUDENTID=35EGM7D45W
STAGE.ACCESSCODE=7MNT2R2F

STAGE.USEREMAIL=
STAGE.PASSWORD=


